instrumentation:
  excludes: [
    '*.js',
    'docs/**',
    'reports',
    'typings',
    'ts/*',
    'node_modules',
    '**/spec/**',
    'examples/**',
    'typings/**',
  ]
  include-all-sources: true
reporting:
  dir: './reports/coverage'
  print: detail